import { test, expect } from '@playwright/test'
test('overview, exact-year selection, rankings, comparison, sources and trends',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/')
 await expect(page.getByText('API connected')).toBeVisible()
 await expect(page.getByRole('heading',{name:'How is Melaka performing?'})).toBeVisible()
 await expect(page.locator('.metric-card').first()).toContainText('2024')
 await page.locator('.metric-card').first().locator('summary').click()
 await expect(page.locator('.metric-card').first()).toContainText('gdp_state_real_supply')
 await expect(page.locator('.metric-card').filter({has:page.getByRole('heading',{name:'Unemployment rate',exact:true})})).toContainText('No observation available')
 await page.getByRole('button',{name:'Latest available',exact:true}).click()
 await expect(page.getByText('Observation years differ between indicators.',{exact:false})).toBeVisible()
 await expect(page.locator('.metric-card').first()).toContainText('2025')
 await page.getByRole('button',{name:'Same year',exact:true}).click()
 await page.getByRole('link',{name:'Rankings',exact:true}).click()
 await expect(page.locator('tbody tr')).toHaveCount(13)
 await expect(page.locator('tbody tr.highlight')).toContainText('Melaka')
 await page.getByLabel('Comparison universe').selectOption('true')
 await expect(page.locator('tbody tr')).toHaveCount(16)
 await page.getByRole('link',{name:'Trends',exact:true}).click()
 await expect(page.locator('.recharts-surface').first()).toBeVisible()
 await page.getByRole('checkbox',{name:'Show government transition'}).check()
 await expect(page.getByText('31 March 2023:',{exact:false})).toBeVisible()
 await page.getByRole('link',{name:'Compare',exact:true}).click()
 await expect(page.locator('.compare-table tbody tr')).toHaveCount(8)
 await expect(page.locator('.compare-table')).toContainText('No observation available')
 await page.getByRole('link',{name:'Raw data',exact:true}).click()
 await page.getByRole('combobox',{name:'State',exact:true}).selectOption('Melaka')
 await page.getByRole('combobox',{name:'Year',exact:true}).selectOption('2024')
 await expect(page.locator('tbody tr')).toHaveCount(1)
 const download=page.waitForEvent('download')
 await page.getByRole('button',{name:'Export this page as CSV'}).click()
 expect((await download).suggestedFilename()).toContain('hies_state')
 expect(errors).toEqual([])
})
test('mobile overview stays within viewport',async({page})=>{
 await page.setViewportSize({width:390,height:844})
 await page.goto('/')
 await expect(page.locator('.metric-card').first()).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
 await page.screenshot({path:'reports/mobile.png',fullPage:true})
})
test('desktop overview screenshot',async({page})=>{
 await page.setViewportSize({width:1440,height:1080})
 await page.goto('/')
 await expect(page.locator('.metric-card').first()).toContainText('2024')
 await page.screenshot({path:'reports/desktop.png',fullPage:true})
})
test('quarterly unemployment keeps quarters explicit', async ({page}) => {
 await page.goto('/unemployment')
 await expect(page.getByRole('heading', {name:'Unemployment, quarter by quarter.'})).toBeVisible()
 await expect(page.locator('.metric-card .year')).toHaveText(/\d{4}-Q[1-4]/)
 await expect(page.locator('.table-wrap').first().locator('tbody tr')).toHaveCount(13)
 await page.getByRole('combobox', {name:'Quarter',exact:true}).selectOption('2024-Q4')
 await expect(page.locator('.metric-card .year')).toHaveText('2024-Q4')
 await expect(page.locator('.table-wrap').first().locator('tbody tr').first()).toContainText('2024-Q4')
 await page.getByRole('combobox', {name:'Comparison universe',exact:true}).selectOption('true')
 await expect(page.locator('.table-wrap').first().locator('tbody tr')).toHaveCount(16)
 await expect(page.locator('.recharts-surface').first()).toBeVisible()
})
