import { Link } from 'react-router-dom'
import { ArrowRight, ChartNoAxesCombined, House, BriefcaseBusiness } from 'lucide-react'
import { useStateOverview } from '../hooks/queries'
import type { Selection } from '../types/api'
import { MetricCard, ModeControl, Note, PageTitle, Status } from '../components/Common'
export default function Home({selection,onChange}:{selection:Selection;onChange:(s:Selection)=>void}) {
 const q=useStateOverview('Melaka',selection)
 const groups=[{title:'Economy',description:'Output, industrial structure and productivity',icon:ChartNoAxesCombined,ids:['real_gdp','gdp_growth','gdp_per_capita','manufacturing_share','labour_productivity','services_share','agriculture_share','construction_share']},{title:'Households',description:'Income, expenditure and the distribution of prosperity',icon:House,ids:['median_household_income','mean_household_income','gini','poverty','mean_household_expenditure']},{title:'Labour',description:'Participation and opportunities to work',icon:BriefcaseBusiness,ids:['unemployment','labour_force_participation','employment']}]
 return <><PageTitle eyebrow="THE MELAKA OVERVIEW" title="How is Melaka performing?">Explore the economy, household welfare and labour market through official data.</PageTitle><ModeControl selection={selection} onChange={onChange}/><Note>{selection.mode==='latest'?<>Latest available <strong>annual and survey</strong> data. {q.data?.mixed_years?'Observation years differ between indicators.':'Each indicator displays its observation year.'}</>:<>All current values are restricted to <strong>{selection.year}</strong>. Missing observations remain unavailable.</>}</Note><Status pending={q.isPending} error={q.error}/>
 {q.data && groups.map(group=><section className="dashboard-section" key={group.title}><div className="section-heading"><div className="section-icon"><group.icon size={21}/></div><div><h2>{group.title}</h2><p>{group.description}</p></div><Link to="/rankings">Explore rankings <ArrowRight size={15}/></Link></div><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4">{group.ids.map(id=>q.data.metrics.find(m=>m.id===id)).map(m=>m&&<MetricCard key={m.id} metric={m}/>)}</div></section>)}
 <Note><Link className="text-link" to="/unemployment">Explore quarterly unemployment: newer observations, quarter-by-quarter trends and state rankings <ArrowRight size={16}/></Link></Note><section className="welfare"><span className="eyebrow">OUTPUT & WELLBEING</span><h2>Is economic growth reaching households?</h2><p>GDP measures total economic output. Household income measures income received by households. They can move differently. Income is nominal; real GDP removes price effects. These indicators alone do not establish causality.</p><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4">{q.data?.metrics.filter(m=>['real_gdp','median_household_income','gini','poverty'].includes(m.id)).map(m=><MetricCard key={m.id} metric={m}/>)}</div><Link className="text-link" to="/trends">Inspect the historical observations <ArrowRight size={16}/></Link></section></>
}
