import { useState } from 'react'
import type { Selection } from '../types/api'
import { useRankings } from '../hooks/queries'
import { MetricSelect, ModeControl, Note, PageTitle, SourceDetails, Status } from '../components/Common'
import { changeText, formatValue } from '../utils/format'
export default function Rankings({selection,onChange}:{selection:Selection;onChange:(s:Selection)=>void}) {
 const [metric,setMetric]=useState('median_household_income')
 const q=useRankings(metric,selection.mode==='same-year'?selection.year:undefined,selection.include)
 return <><PageTitle eyebrow="STATE RANKINGS" title="Where does Melaka stand?">Compare the same indicator in the same year. Rankings describe relative values, not overall performance.</PageTitle><div className="filters"><MetricSelect value={metric} onChange={setMetric}/></div><ModeControl selection={selection} onChange={onChange}/><Status pending={q.isPending} error={q.error}/>{q.data && <><div className="table-heading"><h2>{q.data.states[0]?.label} <span className="year">{q.data.year}</span></h2><span>{q.data.comparison_count} of {q.data.eligible_count} areas with observations</span></div><Note>{q.data.states[0]?.ranking_direction==='ascending'?'Rank 1 is the lowest value.':'Rank 1 is the highest value.'} Ties share a rank; the next rank is skipped. {q.data.missing_states.length>0 && `Unavailable: ${q.data.missing_states.join(', ')}.`}</Note><div className="table-wrap"><table><thead><tr><th>Rank</th><th>State</th><th>Value · {q.data.states[0]?.unit}</th><th>Observation</th><th>Previous value</th><th>Change</th><th>Provenance</th></tr></thead><tbody>{q.data.states.map(m=><tr key={m.state} className={m.state==='Melaka'?'highlight':''}><td><span className="rank-number">{m.rank??'—'}</span></td><td className="state-cell">{m.state}{m.state==='Melaka'&&<span className="tag">MELAKA</span>}</td><td className="number">{formatValue(m.value,m.unit)}</td><td>{m.year}</td><td>{m.previous?`${formatValue(m.previous.value,m.unit)} (${m.previous.year})`:'—'}</td><td>{m.value===null?'No observation available':changeText(m)}</td><td><SourceDetails source={m.source} year={m.year}/></td></tr>)}</tbody></table></div></>}</>
}
