import { useState } from 'react'
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, ReferenceLine, Legend } from 'recharts'
import { useCatalogue, useTrend } from '../hooks/queries'
import { MetricSelect, Note, PageTitle, SourceDetails, Status } from '../components/Common'
import { formatValue } from '../utils/format'
export default function Trends() {
 const [metric,setMetric]=useState('real_gdp'),[state,setState]=useState('Melaka'),[comparison,setComparison]=useState('Johor'),[marker,setMarker]=useState(false)
 const catalogue=useCatalogue(),primary=useTrend(metric,state),secondary=useTrend(metric,comparison)
 const options=[...(catalogue.data?.states??[]),...(catalogue.data?.territories??[])]
 // Align observed points for rendering only; no interpolation or analytical calculations.
 const points=new Map<number,Record<string,number>>()
 primary.data?.observations.forEach(o=>points.set(o.year,{year:o.year,primary:o.value}))
 secondary.data?.observations.forEach(o=>points.set(o.year,{...points.get(o.year),year:o.year,secondary:o.value}))
 const rows=[...points.values()].sort((a,b)=>a.year-b.year)
 const unit=primary.data?.unit??''
 return <><PageTitle eyebrow="HISTORICAL TRENDS" title="Look beyond a single year.">Actual annual and survey observations from 2015 onwards, where available.</PageTitle><div className="filters"><MetricSelect value={metric} onChange={setMetric}/><label>State<select value={state} onChange={e=>setState(e.target.value)}>{options.map(s=><option key={s}>{s}</option>)}</select></label><label>Comparison state<select value={comparison} onChange={e=>setComparison(e.target.value)}><option value="">None</option>{options.map(s=><option key={s}>{s}</option>)}</select></label></div><Status pending={primary.isPending} error={primary.error}/>{comparison && <Status pending={secondary.isPending} error={secondary.error}/>}<div className="chart-panel"><div className="table-heading"><div><h2>{primary.data?.label}</h2><p>{unit} · actual observations</p></div><label className="checkbox"><input type="checkbox" checked={marker} onChange={e=>setMarker(e.target.checked)}/> Show government transition</label></div>{rows.length ? <ResponsiveContainer width="100%" height={370}><LineChart margin={{top:25,right:30,bottom:15,left:20}} data={rows}><CartesianGrid strokeDasharray="3 4" vertical={false} stroke="#e2e8e5"/><XAxis type="number" dataKey="year" domain={['dataMin','dataMax']} allowDecimals={false}/><YAxis width={85} tickFormatter={v=>formatValue(Number(v),unit)}/><Tooltip labelFormatter={v=>`Observation: ${v}`} formatter={v=>[`${formatValue(Number(v),unit)} ${unit}`]}/><Legend/><Line type="linear" dataKey="primary" name={state} stroke="#16765c" strokeWidth={3} dot={{r:4}} connectNulls={false}/>{comparison&&<Line type="linear" dataKey="secondary" name={comparison} stroke="#b48b48" strokeWidth={2} dot={{r:4}} connectNulls={false}/>} {marker&&<ReferenceLine x={2023.244} stroke="#66766e" strokeDasharray="4 4" label={{value:'31 Mar 2023',position:'insideTopRight'}}/>}</LineChart></ResponsiveContainer>:<p>No observations available for this selection.</p>}</div><Note>Dots represent actual observations. Lines connect observed values only; no missing survey years are estimated. {marker&&<span>31 March 2023: Ab Rauf Yusoh became Chief Minister. Context only; chronology does not establish causality. <a href={primary.data?.annotation.source_url} target="_blank" rel="noreferrer">Official timeline source ↗</a></span>}</Note><details className="observation-table"><summary>Inspect observations and sources</summary><div className="table-wrap"><table><thead><tr><th>State</th><th>Year</th><th>Value · {unit}</th><th>Source</th></tr></thead><tbody>{[primary.data,...(comparison?[secondary.data]:[])].flatMap(t=>t?.observations.map(o=><tr key={`${t.state}-${o.year}`}><td>{t.state}</td><td>{o.year}</td><td>{formatValue(o.value,unit)}</td><td><SourceDetails source={o.source} year={o.year}/></td></tr>)??[])}</tbody></table></div></details></>
}
