"""Generate reproducible verification outputs from the validated source cache."""
import json
from pathlib import Path
from .api.dependencies import engine
from .analysis.catalogue import DEFINITIONS
from .data.service import analytical_data
from .data.registry import REGISTRY
from .data.opendosm import get_dataset_metadata
METRICS=['real_gdp','gdp_growth','gdp_per_capita','median_household_income','mean_household_income','gini','poverty','unemployment','labour_productivity','manufacturing_share']
def number(value):
    return 'Unavailable' if value is None else f'{value:,.3f}'.rstrip('0').rstrip('.')
def table(metrics):
    lines=['| Metric | Value | Year | Rank | Previous | Change |','|---|---:|---:|---|---|---|']
    for m in metrics:
        previous=m['previous'];change=m['change']
        prior=f"{number(previous['value'])} ({previous['year']})" if previous else '—'
        delta=f"{number(change['percent'])}%" if change and change['percent'] is not None else f"{number(change['absolute'])} {change['unit']}" if change else '—'
        lines.append(f"| {m['label']} | {number(m['value'])} {m['unit']} | {m['year']} | {m['rank_label'] or 'Unavailable'} | {prior} | {delta} |")
    return '\n'.join(lines)
def main():
    e=engine();out=Path(__file__).parents[2]/'reports';out.mkdir(exist_ok=True)
    latest=e.overview('Melaka','latest',None,False);same=e.overview('Melaka','same-year',2024,False)
    rankings={key:e.rankings(key,2024,False) for key in DEFINITIONS}
    trends={key:e.trend(key,'Melaka',2015) for key in DEFINITIONS}
    metadata={key:get_dataset_metadata(key) for key in REGISTRY}
    payload={'latest':latest,'same_year_2024':same,'rankings_2024':rankings,'trends':trends,'sources':metadata,'discrepancies':analytical_data()[1]}
    (out/'verification.json').write_text(json.dumps(payload,indent=2))
    text=['# Melaka — verification from official datasets','Generated by `cd backend && python -m app.verify`. No conversational figures are used as inputs. All rankings default to the 13 states. Competition ties use 1, 1, 3. Source vintages and SHA-256 hashes are in verification.json.','## Melaka — Latest Available',f"Mixed years: {latest['mixed_years']}. Latest refers to the curated annual/survey sources, not all DOSM publications.",table([m for m in latest['metrics'] if m['id'] in METRICS]),'## Melaka — 2024',table([m for m in same['metrics'] if m['id'] in METRICS]),'## Melaka State Rankings — 2024']
    for key,result in rankings.items():
        text.extend([f"### {DEFINITIONS[key].label}",'| State | Value | Rank |','|---|---:|---:|'])
        for m in result['states']:text.append(f"| {m['state']} | {number(m['value'])} {m['unit']} | {m['rank'] or 'Unavailable'} |")
    text.append('## Melaka Trend — 2015 to latest')
    for key,result in trends.items():
        text.extend([f"### {result['label']} ({result['unit']})",'| Year | Value | Source dataset |','|---|---:|---|'])
        for o in result['observations']:text.append(f"| {o['year']} | {number(o['value'])} | {o['source']['dataset']} |")
    text.extend(['## Discrepancy audit',f"{len(payload['discrepancies'])} differences between overlapping official household sources. HIES is used for overlapping years; details are recorded in verification.json.",'Earlier figures in the project brief are examples rather than verified claims; none are used as application inputs. The source-derived results above supersede those examples.','## Sources'])
    for meta in metadata.values():text.append(f"- [{meta['title']}]({meta['source_url']}) — latest {meta.get('max_year')}; retrieved {meta.get('retrieved_at')}; local key `{meta['id']}`.")
    text.extend(['## Caveats','Annual labour-force data in the registered source end in 2023. No 2024 estimate is substituted. GDP per capita is nominal and the registered workbook supplies 2023–2025. Productivity is the published DOSM series, not a ratio constructed using labour-force survey employment. Kuala Lumpur productivity includes Putrajaya. GDP at constant prices and nominal household income cannot be treated as the same concept. The 2020 modelled income estimates are excluded from actual survey trends. No causal attribution is made.'])
    (out/'verification.md').write_text('\n\n'.join(text).replace('|\n\n|', '|\n|')+'\n')
    print(out/'verification.md')
if __name__=='__main__':main()
